### ISSUE TITLE
为什么不直接往linux kernel贡献？

### ISSUE THREAD

**Issue by netroby** [Tencent/TencentOS-kernel#1]
为什么不往linux kernel贡献？
独立开发，维护的成本非常高，且如果一直自己玩，离主干linux kernel只会差异越来越大。当差异达到百万行代码。。你如何保证能适时更新到官方最新的版本。

**Comment by maplebeats** [comment]
官方哪有那么容易贡献，一般都是两条线一起跑的，业务和社区并行，又不冲突

**Comment by gxm-newton** [comment]
> 为什么不往linux kernel贡献？
> 独立开发，维护的成本非常高，且如果一直自己玩，离主干linux kernel只会差异越来越大。当差异达到百万行代码。。你如何保证能适时更新到官方最新的版本。

腾讯往社区push的补丁不少啊。
还有就是，作为大企业来讲，运营海量服务器，肯定需要一个比较稳定，高效的版本，如果要满足这两点，那用最新版内核，必然是不可能的。
所以你可以看到大公司基本都是选定了社区某个longterm版本，自己修复运营的bug, 解决遇到的性能问题，同时也会backport社区的补丁，支持新特性。
然后一个版本会运营好几年，再切换到社区较新的longterm版，继续开始。

**Comment by butterl** [comment]
4.14  Jan, 2024 EOL，即使暂时上不了主干，可以考虑往那几个mantainer的tree里拱拱 :)

不过项目名叫 TencentOS-kernel 是说 还有内核以上的部分还没开出来，还是说主要为了外部维护patchlist 顺带做了开源义务履行?

**Comment by netroby** [comment]
不能进入mainline，感觉还是自high。随着开发人员变动，或者离职，就没有多大动力去推动迭代和开发了。

**Comment by gxm-newton** [comment]
> 不能进入mainline，感觉还是自high。随着开发人员变动，或者离职，就没有多大动力去推动迭代和开发了。

腾讯往社区push的补丁不少啊，  你可以多留意下。
另外我感觉开源&分享的方式不一定只有进mainline一种吧，很多没进mainline的特性，依然有很多人在用啊。

**Comment by netroby** [comment]
@gxm-newton 很多人在用。看是不是平台比较牛逼。 腾讯云平台牛逼，我知道。

离开了这个平台呢？

用户会主动下载安装使用非mainline的内核吗？

如果进入了mainline，用户不必做决断，因为已经内置原生就有这些特性。

**Comment by gxm-newton** [comment]
> @gxm-newton 很多人在用。看是不是平台比较牛逼。 腾讯云平台牛逼，我知道。
> 
> 离开了这个平台呢？
> 
> 用户会主动下载安装使用非mainline的内核吗？
> 
> 如果进入了mainline，用户不必做决断，因为已经内置原生就有这些特性。

恩，其实我想举的例子是。。阿里的fullnat啥的，用的人真的很多，但是mainline一直都没收啊。
不过确实我们还是要更加的积极的多想社区push 更多的内容才行，争取让mainline接收。 ^_^

**Comment by netroby** [comment]
加油。 希望看到以后Linux kernel，是中国人贡献最多。

**Comment by gxm-newton** [comment]
> 加油。 希望看到以后Linux kernel，是中国人贡献最多。

^_^， 谢谢，共勉！
