### ISSUE TITLE
page cache limit 特性为什么只回收文件页不回收匿名页

### ISSUE THREAD

**Issue by huhaipeng** [Tencent/TencentOS-kernel#108]
看了page cache limit的代码，我有一个疑问，为什么只回收文件页不回收匿名页？我觉得匿名页也是可以根据系统需要做一定比例的回收。还是说我的理解有问题，回收匿名页会有什么坑吗？

**Comment by huhaipeng** [comment]
@honkiko @hzlzh @oilbeater @yyx

**Comment by joeytsq** [comment]
@zhipingdu111

**Comment by 204184251HQG** [comment]
因为匿名页需要swap，比较耗时，相比文件映射，会触发大量io

**Comment by huhaipeng** [comment]
> 因为匿名页需要swap，比较耗时，相比文件映射，会触发大量io
照抄官方文档有意思？

**Comment by huhaipeng** [comment]
> 因为匿名页需要swap，比较耗时，相比文件映射，会触发大量io

照抄官方文档有意思？
