### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/TencentOS-kernel#15]
Memory is allocated
https://github.com/Tencent/TencentOS-kernel/blob/f9a96d3888b0e468d9f880c14df354c19d2fb183/tools/objtool/elf.c#L161
but at the end of function，never free it
https://github.com/Tencent/TencentOS-kernel/blob/f9a96d3888b0e468d9f880c14df354c19d2fb183/tools/objtool/elf.c#L178

**Comment by gxm-newton** [comment]
false positive
