### ISSUE TITLE
离线调度算法(BT)啥时候开源

### ISSUE THREAD

**Issue by xuzhichuang** [Tencent/TencentOS-kernel#2]
很期待~~~

**Comment by gatieme** [comment]
之前也比较关注你们的 BT scheduling class。

https://lore.kernel.org/patchwork/cover/1092086/
https://lkml.org/lkml/2019/6/21/77

也大致看了你们的适用场景，也想具体测试下。
不知道贵部有可以公开的测试方法和测试用例么

谢谢。

**Comment by gxm-newton** [comment]
> 之前也比较关注你们的 BT scheduling class。
> 
> https://lore.kernel.org/patchwork/cover/1092086/
> https://lkml.org/lkml/2019/6/21/77
> 
> 也大致看了你们的适用场景，也想具体测试下。
> 不知道贵部有可以公开的测试方法和测试用例么
> 
> 谢谢。

如我楼上回复的，我们会在节前后者节后，把BT调度push到内核里，同时附上完整的设计文档，使用说明，如果大家需要，我们会提供一些典型的testcase

**Comment by gatieme** [comment]
OK,谢谢，静候更新。。。

**Comment by gatieme** [comment]
OK.谢谢。
静候更新。

**Comment by gxm-newton** [comment]
已开源,close
