### ISSUE TITLE
overlay2 dosesn't work with nfsv4 mountpoint subdir as lower-dir

### ISSUE THREAD

**Issue by honkiko** [Tencent/TencentOS-kernel#20]
nfsv4作为overlayfs lower层时，在overlayfs工作目录的子目录创建文件和目录没有权限。

原因：nfsv4 acl和posix acl不兼容，由于acl都是以xattr保存，overlayfs copy_up机制会将文件xattr中的nfsv4_acl copy_up到上层upper文件系统如ext4，其使用posix acl，导致没有权限创建文件和目录。当前5.7内核已修复该问题。https://github.com/torvalds/linux/blob/v5.7/fs/overlayfs/copy_up.c#L118

**Comment by brookxu-cn** [comment]
多谢 :)，已修复这个问题

**Comment by brookxu-tx** [comment]
多谢 :)，问题已经fix掉
