### ISSUE TITLE
kernel.container_cpuquota_aware not work

### ISSUE THREAD

**Issue by honkiko** [Tencent/TencentOS-kernel#22]
kernel.container_cpuquota_aware 这个开关有问题，无论是在主机还是在容器设置，无论是设置0还是1， 结果都一样，容器里面的/proc/cpuinfo都没有根据容器的cpuquota来换算。 客户期望都是要根据cpuquota来换算。

建议缺省要开启这个特性，容器里面的/proc/cpuinfo要根据容器的cpuquota来换算。

另外，这个开关可以去掉，目前没有这个需求。
或者作为系统级的开关，可读。 不需要作为容器级的开关。

**Comment by shookliu** [comment]
已修复该问题
这个开关默认是开启的，考虑到兼容其它场景，还是需要保留的
