### ISSUE TITLE
sched_setscheduler接口调用失败

### ISSUE THREAD

**Issue by sidedoorleftroad** [Tencent/TencentOS-kernel#227]
版本：4.14.105-19-0022
编译安装之后，开启offline_class和offline_group
重启后/proc/bt_stat以及cgroup下相关的bt文件存在

尝试使用sched_setscheduler()设置某个进程为离线进程，发现设置失败，求助~~~

[root@10 ~]# uname -r
4.14.105-19-0023+

./set_sched 2675
pid: 2675
result: 0
result: -1
errorno: 3

set_sched代码如下：
#include <sched.h>
#include <stdio.h>
#include <errno.h>

int main(int argc,char *argv[]) {
  struct sched_param param;
  param.sched_priority = 0;
  if (argc < 2) {
    printf("no pid specified\n");
    return 0;
  }
  printf("pid: %s\n", argv[1]);

  int n_pid = atoi(argv[1]);

  int r = sched_setscheduler(n_pid, 3, &param);
  printf("result: %d\n", r);

  r = sched_setscheduler(n_pid, 7, &param);
  printf("result: %d\n", r);
  printf("errorno: %d\n", errno);
  // printf("%s\n", strerror(errno));

  return 0;
}

将进程设置policy=3是正常，但是设置为7的时候就不行了。

**Comment by sidedoorleftroad** [comment]
@kaixuxiakx 请帮忙给看一下哈

**Comment by sidedoorleftroad** [comment]
补充，在启动参数中，把offline_group去掉，只保留offline_class，再次测试就可以成功了，可能和我环境上cgroup相关的东东有关系？

**Comment by netpy** [comment]
你好，能详细介绍一下你的启动参数是如何设置的吗？我是用rpm升级内核之后，并没有看到/proc/bt_stat，使用你的测试程序进行测试，错误码是22
