### ISSUE TITLE
离线调度算法没有被启用生效

### ISSUE THREAD

**Issue by blackleave** [Tencent/TencentOS-kernel#23]
make menuconfig勾选了离线调度算法并成功编译，重启进入新内核后，cgroup目录下并没有出现离线调度相关的文件，调用sched_setschedluer()设置调度类型为7，提示参数不合法。
启用离线调度算法是否需要打开开关？

**Comment by chenhe-dev** [comment]
启动离在线调度算法需要在启动参数中添加`offline_class`, 如需要cgroup支持, 还需要添加`offline_group`.
参见: https://github.com/Tencent/TencentOS-kernel#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by blackleave** [comment]
感谢解答，已成功启用
