### ISSUE TITLE
热补丁工具没有开源

### ISSUE THREAD

**Issue by gatieme** [Tencent/TencentOS-kernel#3]
看到你们基于内核中适配了 ARM64 的热补丁。
但是 kpatch 工具没有开源。

是不是这组补丁
https://www.redhat.com/archives/kpatch/2019-July/msg00000.html

**Comment by gxm-newton** [comment]
> 看到你们基于内核中适配了 ARM64 的热补丁。
> 但是 kpatch 工具没有开源。
> 
> 是不是这组补丁
> https://www.redhat.com/archives/kpatch/2019-July/msg00000.html

是这组热补丁，用户态kpatch我们正在思考怎么个开源法， 毕竟对kpatch改动是有，但是呢，也不是很大，也把patch都push给了kpatch

**Comment by gatieme** [comment]
工具应该很多自己适配的东西，最好还是你们开源在github上好，

社区的还是太保守。
而且本身社区kpatch的流程和业务需求并不一定就适合自己实际的业务环境。

**Comment by gxm-newton** [comment]
> 工具应该很多自己适配的东西，最好还是你们开源在github上好，
> 
> 社区的还是太保守。
> 而且本身社区kpatch的流程和业务需求并不一定就适合自己实际的业务环境。

好的， 我们后面再开个git库
