### ISSUE TITLE
sched_bt_runtime_us  can't limit offline process use cpu

### ISSUE THREAD

**Issue by wxyh** [Tencent/TencentOS-kernel#53]
I start with offline_class and offfline_group, echo 1 > cpu.offline in offline process cgroup, set sched_bt_runtime_us value in /proc/sys/kernel, but can't limit offline process use cpu.
![image](https://user-images.githubusercontent.com/50309350/106560672-5a3bc900-6562-11eb-8e09-9bce0fd7092e.png)
![image](https://user-images.githubusercontent.com/50309350/106560603-3bd5cd80-6562-11eb-940b-83a71501bb48.png)
![image](https://user-images.githubusercontent.com/50309350/106560644-4b551680-6562-11eb-812a-3e301574bfa5.png)

**Comment by heddchen** [comment]
Please assign offfline throttling percentage [0-100] to /proc/offline/cpuX file :-)

> set sched_bt_runtime_us value in /proc/sys/kernel, but can't limit offline process use cpu.

**Comment by wxyh** [comment]
Thanks, it works
