### ISSUE TITLE
system.slice not included in cpuset subsystem

### ISSUE THREAD

**Issue by huangjw08** [Tencent/TencentOS-kernel#59]
**Description**
Install TencentOS-Server-3.1-for-x86_64-TK4-20210303.iso on my virtual machine，and couldn't find system.slice in /sys/fs/cgroup/cpuset/ directory.

> [root@TENCENT64 cgroup]# find /sys/fs/cgroup/ -name "system.slice"
/sys/fs/cgroup/memory/system.slice
/sys/fs/cgroup/blkio/system.slice
/sys/fs/cgroup/devices/system.slice
/sys/fs/cgroup/pids/system.slice
/sys/fs/cgroup/cpu,cpuacct/system.slice
/sys/fs/cgroup/systemd/system.slice

**Problem**
please confirm whether the dir /sys/fs/cgroup/cpuset/system.slice exist?

**Comment by liuyuhang** [comment]
systemd的官方文档，明确的表示了在cgroupV1中现在及以后都不会对cpuset进行支持。：https://systemd.io/CGROUP_DELEGATION/
