### ISSUE TITLE
Bugs in the TencentOS-kernel or Linux kernel

### ISSUE THREAD

**Issue by XidianGeneral** [Tencent/TencentOS-kernel#6]
Hello,

I find some bugs in the TencentOS-kernel code, but I am not sure whether they are derived from the Linux kernel. So can I report bugs or submit patches here?

**Comment by gxm-newton** [comment]
could email the bug to tencent_os@tencent.com ? . or you cuold just post the bug here, thanks

**Comment by gxm-newton** [comment]
yes, you may create a merge request, or issue
