### ISSUE TITLE
offline_group 模式下如何能够限制 docker 容器中离线使用 CPU 的比例？

### ISSUE THREAD

**Issue by DavadDi** [Tencent/TencentOS-kernel#76]
offline_group 模式下如何能够限制 docker 容器中离线使用 CPU 的比例，在不启用 offline_group 的模式下可以单独设置 /proc/sys/kernel/sched_bt_runtime_us 值限制 bt 类进程的使用率，该参数在设置 offline_group 以后不再生效

**Comment by cndoit18** [comment]
相同的问题 #53
