### ISSUE TITLE
BT离线调度器不起作用

### ISSUE THREAD

**Issue by cndoit18** [Tencent/TencentOS-kernel#87]
(使用master分支自行编译)

您好，我们在开启BT_SCHED之后，将对应的进程都设置成离线BT。
然后使用stress-ng进行压测，发现对应的p99/p95几乎和不开启离线没啥区别

是只需要设置完sched_setscheduler之后，bt的进程就几乎不会影响其他进程?

我们也通过kernel.sched_bt_runtime_us将离线服务压制到50%，但是已然干扰其他进制

**Comment by cndoit18** [comment]
看起来是我自己的测试逻辑导致的。

**Comment by cndoit18** [comment]
update: 当前版本会产生多线程干扰，需要关闭多线程功能

**Comment by lubinszARM** [comment]
> update: 当前版本会产生超线程干扰，需要关闭超线程功能

WOW. 这个应该是很大的缺陷了吧。毕竟大多数环境都是要开启超线程的。

**Comment by cndoit18** [comment]
> > update: 当前版本会产生超线程干扰，需要关闭超线程功能
> 
> WOW. 这个应该是很大的缺陷了吧。毕竟大多数环境都是要开启超线程的。

是的

**Comment by ccl0326** [comment]
cc @yongduan @kaixuxiakx 
不好意思，如这个issue描述，超线程是一个普遍场景，有哪位同学能确认一下目前是否有问题，以及未来某个时间节点是否会支持吗

**Comment by cndoit18** [comment]
> 

我email联系过，tencent内部已经解决了，但似乎并不打算开源

**Comment by ccl0326** [comment]
@cndoit18 谢谢及时的回复～
